#pragma once

#include <windows.h>

const LPWSTR monFileExtExc[] = {
	L".EXE", L".DLL", L".SYS", L".drv", L".vxd", L".ocx", L".COM", L".PIF", L".BAT", L".SCR",
	L".PS1", L".VBS", L".VBE", L".JS",  L".JSE", L".WSH", L".MSC", L".vbx", L".fon",
	L".chm", L".chw", L".chi", L".hlp", L".gid", L".lhp", L".its", L".lit", L".h1d", L".h1h",
	L".h1q", L".h1w",L".ebo",L".application",L".GADGET", L".msi", L".MSP", L".HTA", L".CPL",
	L".jar", L".vb", L".PS1XML", L".ps2", L".PS2XML", L".psc1", L".psc2", L".msh",
	L".MSH1", L".MSH2", L".MSHXML", L".MSH1XML", L".MSH2XML", L".SCF", L".lnk", L".INF",
	L".DOC", L".XLS",L".PPT", L".DOCM", L".DOTM", L".XLSM", L".XLTM",L".XLAM",L".PPTM",
	L".POTM",L".PPAM",L".PPSM",L".SLDM",
	NULL
};

const LPWSTR monFileExtData[] = {
	L".pdf", L".txt", L".doc", L".xls", L".ppt", L".pps", L".rtf",	L".docx", L".xlsx", L".pptx",
	L".odt", L".ods", L".xml",
	L".cwp", L".cwt", L".kor",
	L".bwp",
	L".cdbx", L".tgk",
	/*L".mdb", L".mda", L".mde", L".mdt", L".fdb", L".psa",
	L".accdb", L".accde", L".accda", L".accdu", L".uot", L".fodt", L".ott", L".sxw",
	L".WPD", L".wp", L".wp5", L".wp6", L".wpp", L".bk!", L".wcm",
	L".one",	L".ps", L".eps", L".pfa",
	L".qdf",	L".qsd",	L".qbb",	L".B64",	L".wb2",	L".fp7", L".fp12", L".fmp12",
	L".fp5", L".fp3",	L".rtd",	L".MNY", L".m12", L".m14", L".m15", L".mnp", L".mne",
	L".DOC2", L".DOC3", L".wri", L".lwp", L".123", L".wk3", L".wk4", L".wk5",
	L".WK1", L".wk5",	L".mpx",	L".cwk",	L".djvu", L".pwi", L".psw", L".tmd", L".tmv",
	L".WKS1", L".wks", L".kwd",  L".ai", L".ait", L".ole2", L".dot", L".xla", L".ppa", L".pot",
	L".sdw", L".db", L".vsd", L".msg", L".odf", L".odg", L".odp", L".odb"*/
	NULL
};

const LPWSTR monFileExtArc[] = {
	L".zip", //L".pages",L".B64",L".arj",L".xz",  L".hqx",L".lzop", L".lzo", L".sqx", L".egg", L".fbf", L".kgb",	L".sea", L".sitx", L".sit", L".ace",	L".JAR1", L".jar", L".xps", L".apk", L".cbr", L".emz",L".ova", L".BZ2", L".tbz", 
	L".rar", L".gz", L".tgz",
	L".7z", L".tar", L".cab",
	L".alz",
	NULL
};

const LPWSTR monFileExtVideo[] = {
	L".AVI", L".mpg", L".mpe", L".mpeg", L".vob",
	L".MOV", L".mp4",	L".3GP",	L".3gpp",
	L".rm", L".rmvb",
	L".wmv", L".webm", L".flv",

	/*L".asf", L".wma", L".dvr-ms", L".MP4S",	L".dcr",L".m2ts", L".ts",L".f4v",
	L".au", L".amr", L".wpL"., L".m3u", L".gvi", L".divx", L".m4a", L".m4p",	L".M4V", L".m4b", L".heic", L".mkv", L".mka",
	L".mid", L".kar", L".midi", L".cda", L".AWB", L".amr",L".3ga", L".3g2",	L".4xm",
	L".auf",	L".dvf; msv", L".snd", L".ulaw; au; snd", L".aif; aiff; caf",
	L".aifc", L".aif", L".aiff", L".cwm",L".mp3", L".wav", L".wtv",	L".rv", L".ra", L".rmj", L".ram", L".rmx",
	L".ogg", L".ogv", L".ogm", L".opus",*/
	NULL
};


const LPWSTR monRegKey[] = {
	L"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Shell",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\Shell",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\Run",
	L"HKCU\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Run",
	L"HKCU\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\RunOnce",
	L"HKCU\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx",
	L"HKCU\\Environment\\UserInitMprLogonScript",
	L"HKCU\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\Load",
	L"HKCU\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\Run",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Terminal Server\\Install\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Terminal Server\\Install\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Terminal Server\\Install\\Software\\Microsoft\\Windows\\CurrentVersion\\Run",
	L"HKLM\\System\\CurrentControlSet\\Control\\Terminal Server\\Wds\\rdpwd\\StartupPrograms",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\AppSetup",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer\\Run",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\System\\Shell",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\Shell",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\SafeBoot\\AlternateShell",
	L"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\TaskMan",
	L"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\UserInit",
	L"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\VmApplet",
	L"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\AlternateShells\\AvailableShells",
	L"HKLM\\Environment\\UserInitMprLogonScript",
	L"HKLM\\SOFTWARE\\Microsoft\\Active Setup\\Installed Components",
	L"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\IconServiceLib",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows CE Services\\AutoStartOnConnect",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows CE Services\\AutoStartDisconnect",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\RunOnce",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Run",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\RunOnce",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Active Setup\\Installed Components",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows CE Services\\AutoStartOnConnect",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows CE Services\\AutoStartOnDisconnect",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Terminal Server\\Install\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnce",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Terminal Server\\Install\\Software\\Microsoft\\Windows\\CurrentVersion\\RunOnceEx",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP - Tcp\\InitialProgram",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Terminal Server\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run",
	L"HKCU\\Software\\Policies\\Microsoft\\Windows\\System\\Scripts\\Logon",
	L"HKCU\\Software\\Policies\\Microsoft\\Windows\\System\\Scripts\\Logoff",
	L"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Startup",
	L"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Logon",
	L"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Logoff",
	L"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Shutdown",
	L"HKLM\\Software\\Policies\\Microsoft\\Windows\\System\\Scripts\\Startup",
	L"HKLM\\Software\\Policies\\Microsoft\\Windows\\System\\Scripts\\Logon",
	L"HKLM\\Software\\Policies\\Microsoft\\Windows\\System\\Scripts\\Logoff",
	L"HKLM\\Software\\Policies\\Microsoft\\Windows\\System\\Scripts\\Shutdown",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Shutdown",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Logoff",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Logon",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Group Policy\\Scripts\\Startup",
	L"HKCU\\SOFTWARE\\Classes\\Protocols\\Filter",
	L"HKCU\\SOFTWARE\\Classes\\Protocols\\Handler",
	L"HKCU\\SOFTWARE\\Microsoft\\Internet Explorer\\Desktop\\Components",
	L"HKCU\\Software\\Classes\\*\\ShellEx\\ContextMenuHandlers",
	L"HKCU\\Software\\Classes\\Drive\\ShellEx\\ContextMenuHandlers",
	L"HKCU\\Software\\Classes\\*\\ShellEx\\PropertySheetHandlers",
	L"HKCU\\Software\\Classes\\AllFileSystemObjects\\ShellEx\\ContextMenuHandlers",
	L"HKCU\\Software\\Classes\\AllFileSystemObjects\\ShellEx\\DragDropHandlers",
	L"HKCU\\Software\\Classes\\AllFileSystemObjects\\ShellEx\\PropertySheetHandlers",
	L"HKCU\\Software\\Classes\\Directory\\ShellEx\\ContextMenuHandlers",
	L"HKCU\\Software\\Classes\\Directory\\ShellEx\\DragDropHandlers",
	L"HKCU\\Software\\Classes\\Directory\\ShellEx\\PropertySheetHandlers",
	L"HKCU\\Software\\Classes\\Directory\\ShellEx\\CopyHookHandlers",
	L"HKCU\\Software\\Classes\\Directory\\Background\\ShellEx\\ContextMenuHandlers",
	L"HKCU\\Software\\Classes\\Folder\\ShellEx\\ContextMenuHandlers",
	L"HKCU\\Software\\Classes\\Folder\\ShellEx\\DragDropHandlers",
	L"HKCU\\Software\\Classes\\Folder\\ShellEx\\PropertySheetHandlers",
	L"HKCU\\Software\\Classes\\Folder\\ShellEx\\ColumnHandlers",
	L"HKCU\\Software\\Classes\\Folder\\ShellEx\\ExtShellFolderViews",
	L"HKCU\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellIconOverlayIdentifiers",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\ShellServiceObjectDelayLoad",
	L"HKCU\\Software\\Classes\\CLSID\\{AB8902B4 - 09CA-4bb6 - B78D - A8F59079A8D5}\\InProcServer32",
	L"HKCU\\Software\\Microsoft\\Ctf\\LangBarAddin",
	L"HKCU\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellServiceObjects",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\SharedTaskScheduler",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellExecuteHooks",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellServiceObjects",
	L"HKLM\\SOFTWARE\\Classes\\Protocols\\Handler",
	L"HKLM\\Software\\Classes\\*\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Classes\\Drive\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Classes\\*\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Classes\\AllFileSystemObjects\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Classes\\AllFileSystemObjects\\ShellEx\\DragDropHandlers",
	L"HKLM\\Software\\Classes\\AllFileSystemObjects\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Classes\\Directory\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Classes\\Directory\\ShellEx\\DragDropHandlers",
	L"HKLM\\Software\\Classes\\Directory\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Classes\\Directory\\ShellEx\\CopyHookHandlers",
	L"HKLM\\Software\\Classes\\Directory\\Background\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Classes\\Folder\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Classes\\Folder\\ShellEx\\DragDropHandlers",
	L"HKLM\\Software\\Classes\\Folder\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Classes\\Folder\\ShellEx\\ColumnHandlers",
	L"HKLM\\Software\\Classes\\Folder\\ShellEx\\ExtShellFolderViews",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellIconOverlayIdentifiers",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\ShellServiceObjectDelayLoad",
	L"HKLM\\Software\\Microsoft\\Ctf\\LangBarAddin",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Explorer\\SharedTaskScheduler",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellExecuteHooks",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellServiceObjects",
	L"HKLM\\Software\\Wow6432Node\\Classes\\*\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Drive\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\*\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\AllFileSystemObjects\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\AllFileSystemObjects\\ShellEx\\DragDropHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\AllFileSystemObjects\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Directory\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Directory\\ShellEx\\DragDropHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Directory\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Directory\\ShellEx\\CopyHookHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Directory\\Background\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Folder\\ShellEx\\ContextMenuHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Folder\\ShellEx\\DragDropHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Folder\\ShellEx\\PropertySheetHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Folder\\ShellEx\\ColumnHandlers",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Folder\\ShellEx\\ExtShellFolderViews",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Explorer\\ShellIconOverlayIdentifiers",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\ShellServiceObjectDelayLoad",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Ctf\\LangBarAddin",
	L"HKCU\\Software\\Microsoft\\Internet Explorer\\UrlSearchHooks",
	L"HKCU\\Software\\Microsoft\\Internet Explorer\\Explorer Bars",
	L"HKCU\\Software\\Microsoft\\Internet Explorer\\Extensions",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Internet Explorer\\Explorer Bars",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Internet Explorer\\Extensions",
	L"HKLM\\Software\\Microsoft\\Internet Explorer\\Toolbar",
	L"HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Browser Helper Objects",
	L"HKLM\\Software\\Microsoft\\Internet Explorer\\Explorer Bars",
	L"HKLM\\Software\\Microsoft\\Internet Explorer\\Extensions",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Internet Explorer\\Toolbar",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Browser Helper Objects",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Internet Explorer\\Explorer Bars",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Internet Explorer\\Extensions",
	L"HKLM\\System\\CurrentControlSet\\Services",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Font Drivers",
	L"HKCU\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Drivers32",
	L"HKCU\\Software\\Classes\\Filter",
	L"HKCU\\Software\\Classes\\CLSID\\{083863F1-70DE - 11d0 - BD40 - 00A0C911CE86}\\Instance",
	L"HKCU\\Software\\Classes\\CLSID\\{AC757296 - 3522 - 4E11 - 9862 - C17BE5A1767E}\\Instance",
	L"HKCU\\Software\\Classes\\CLSID\\{7ED96837 - 96F0 - 4812 - B211 - F13C24117ED3}\\Instance",
	L"HKCU\\Software\\Classes\\CLSID\\{ABE3B9A4 - 257D - 4B97 - BD1A - 294AF496222E}\\Instance",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Windows NT\\CurrentVersion\\Drivers32",
	L"HKCU\\Software\\Wow6432Node\\Classes\\CLSID\\{083863F1-70DE - 11d0 - BD40 - 00A0C911CE86}\\Instance",
	L"HKCU\\Software\\Wow6432Node\\Classes\\CLSID\\{AC757296 - 3522 - 4E11 - 9862 - C17BE5A1767E}\\Instance",
	L"HKCU\\Software\\Wow6432Node\\Classes\\CLSID\\{7ED96837 - 96F0 - 4812 - B211 - F13C24117ED3}\\Instance",
	L"HKCU\\Software\\Wow6432Node\\Classes\\CLSID\\{ABE3B9A4 - 257D - 4B97 - BD1A - 294AF496222E}\\Instance",
	L"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Drivers32",
	L"HKLM\\Software\\Classes\\Filter",
	L"HKLM\\Software\\Classes\\CLSID\\{083863F1-70DE - 11d0 - BD40 - 00A0C911CE86}\\Instance",
	L"HKLM\\Software\\Classes\\CLSID\\{AC757296 - 3522 - 4E11 - 9862 - C17BE5A1767E}\\Instance",
	L"HKLM\\Software\\Classes\\CLSID\\{7ED96837 - 96F0 - 4812 - B211 - F13C24117ED3}\\Instance",
	L"HKLM\\Software\\Classes\\CLSID\\{ABE3B9A4 - 257D - 4B97 - BD1A - 294AF496222E}\\Instance",
	L"HKLM\\Software\\Wow6432Node\\Classes\\Filter",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Windows NT\\CurrentVersion\\Drivers32",
	L"HKLM\\Software\\Wow6432Node\\Classes\\CLSID\\{AC757296 - 3522 - 4E11 - 9862 - C17BE5A1767E}\\Instance",
	L"HKLM\\Software\\Wow6432Node\\Classes\\CLSID\\{7ED96837 - 96F0 - 4812 - B211 - F13C24117ED3}\\Instance",
	L"HKLM\\Software\\Wow6432Node\\Classes\\CLSID\\{ABE3B9A4 - 257D - 4B97 - BD1A - 294AF496222E}\\Instance",
	L"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\BootExecute",
	L"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\SetupExecute",
	L"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\Execute",
	L"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\S0InitialCommand",
	L"HKCU\\Software\\Microsoft\\Command Processor\\Autorun",
	L"HKCU\\SOFTWARE\\Classes\\Exefile\\Shell\\Open\\Command\\(Default)",
	L"HKCU\\SOFTWARE\\Classes\\Htmlfile\\Shell\\Open\\Command\\(Default)",
	L"HKCU\\Software\\Classes\\.exe",
	L"HKCU\\Software\\Classes\\.cmd",
	L"HKLM\\Software\\Microsoft\\Command Processor\\Autorun",
	L"HKLM\\Software\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options",
	L"HKLM\\SOFTWARE\\Classes\\Exefile\\Shell\\Open\\Command\\(Default)",
	L"HKLM\\SOFTWARE\\Classes\\Htmlfile\\Shell\\Open\\Command\\(Default)",
	L"HKLM\\Software\\Classes\\.exe",
	L"HKLM\\Software\\Classes\\.cmd",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Command Processor\\Autorun",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Windows NT\\CurrentVersion\\Image File Execution Options",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\Appinit_Dlls",
	L"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\AppCertDlls",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Windows NT\\CurrentVersion\\Windows\\Appinit_Dlls",
	L"HKLM\\System\\CurrentControlSet\\Control\\Session Manager\\KnownDlls",
	L"HKCU\\SOFTWARE\\Policies\\Microsoft\\Windows\\Control Panel\\Desktop\\Scrnsave.exe",
	L"HKCU\\Control Panel\\Desktop\\Scrnsave.exe",
	L"HKLM\\SYSTEM\\Setup\\CmdLine",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\Taskman",
	L"HKLM\\System\\CurrentControlSet\\Control\\BootVerificationProgram\\ImagePath",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\Credential Providers",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\Credential Provider Filters",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\PLAP Providers",
	L"HKLM\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon\\GpExtensions",
	L"HKLM\\System\\CurrentControlSet\\Services\\WinSock2\\Parameters\\Protocol_Catalog9\\Catalog_Entries",
	L"HKLM\\System\\CurrentControlSet\\Services\\WinSock2\\Parameters\\NameSpace_Catalog5\\Catalog_Entries",
	L"HKLM\\System\\CurrentControlSet\\Services\\WinSock2\\Parameters\\Protocol_Catalog9\\Catalog_Entries64",
	L"HKLM\\System\\CurrentControlSet\\Services\\WinSock2\\Parameters\\NameSpace_Catalog5\\Catalog_Entries64",
	L"HKLM\\System\\CurrentControlSet\\Control\\Print\\Monitors",
	L"HKLM\\System\\CurrentControlSet\\Control\\Print\\Providers",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\SecurityProviders\\SecurityProviders",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Authentication Packages",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Notification Packages",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\Security Packages",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\Lsa\\OSConfig\\Security Packages",
	L"HKLM\\SYSTEM\\CurrentControlSet\\Control\\NetworkProvider\\Order",
	L"HKCU\\Software\\Microsoft\\Office\\Outlook\\Addins",
	L"HKCU\\Software\\Microsoft\\Office\\Excel\\Addins",
	L"HKCU\\Software\\Microsoft\\Office\\PowerPoint\\Addins",
	L"HKCU\\Software\\Microsoft\\Office\\Word\\Addins",
	L"HKCU\\Software\\Microsoft\\Office\\Access\\Addins",
	L"HKCU\\Software\\Microsoft\\Office\\OneNote\\Addins",
	L"HKCU\\SOFTWARE\\Microsoft\\Office test\\Special\\Perf\\(Default)",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Office\\Outlook\\Addins",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Office\\Excel\\Addins",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Office\\PowerPoint\\Addins",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Office\\Word\\Addins",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Office\\Access\\Addins",
	L"HKCU\\Software\\Wow6432Node\\Microsoft\\Office\\OneNote\\Addins",
	L"HKCU\\SOFTWARE\\Wow6432Node\\Microsoft\\Office test\\Special\\Perf\\(Default)",
	L"HKLM\\Software\\Microsoft\\Office\\Outlook\\Addins",
	L"HKLM\\Software\\Microsoft\\Office\\Excel\\Addins",
	L"HKLM\\Software\\Microsoft\\Office\\PowerPoint\\Addins",
	L"HKLM\\Software\\Microsoft\\Office\\Word\\Addins",
	L"HKLM\\Software\\Microsoft\\Office\\Access\\Addins",
	L"HKLM\\Software\\Microsoft\\Office\\OneNote\\Addins",
	L"HKLM\\SOFTWARE\\Microsoft\\Office test\\Special\\Perf\\(Default)",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Office\\Outlook\\Addins",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Office\\Excel\\Addins",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Office\\Access\\Addins",
	L"HKLM\\Software\\Wow6432Node\\Microsoft\\Office\\OneNote\\Addins",
	L"HKLM\\SOFTWARE\\Wow6432Node\\Microsoft\\Office test\\Special\\Perf\\(Default)",
	NULL
};